### ISSUE TITLE
play/pause method

### ISSUE THREAD

**Issue by kg912** [mpachnis/mp-video#1]
Hi, I'm using mp-video in an application which requires me to pause video playback when a certain condition occurs. I wanted to know if there's a way I could pause video playback programmatically.

**Comment by mpachnis** [comment]
I created a small demo, I have some problems to pause the youtube video but I'll take a look on this and I'll update the post

https://jsfiddle.net/8bx0xLjk/

**Comment by kg912** [comment]
Thanks a lot. That worked for HTML5 videos. Autoplay for HTML5 videos didn't work for me. can you post an example for that too?

**Comment by mpachnis** [comment]
Glad that worked for you. Just add the `video-auto-play` property to the element.

```html
<mp-video html-video video-auto-play></mp-video>
```

**Comment by mpachnis** [comment]
I'm going to close this issue. If you need further help or info feel free to re-open or open a new one.
