### ISSUE TITLE
Hybrid element or Polymer 2

### ISSUE THREAD

**Issue by JaySunSyn** [mpachnis/mp-video#2]
Hi! Many thanks for this element!

Any plans to port it to Polymer 2 or Hybrid?

Thanks!

**Comment by mpachnis** [comment]
Hi,

I'll upload a polymer 2 version and I'll keep a branch for v.1, hopefully in the weekend or next week.

Thanks.

**Comment by JaySunSyn** [comment]
Awesome! Looking forward!

**Comment by mpachnis** [comment]
Version 2.0 is ready. you can get it from bower, yarn or here.
Let me know if there any issue.

**Comment by JaySunSyn** [comment]
Thanks a lot!! Great work!
