### ISSUE TITLE
Reload same player with a new video on id change

### ISSUE THREAD

**Issue by wouterz** [mpachnis/mp-video#3]
how do you suggest doing this?

changing the video id and calling the function again gets some kind of error by froogaloops

**Comment by mpachnis** [comment]
Can you share an example on how do you do that?

**Comment by wouterz** [comment]
`<mp-video vimeo video-id=[[videoid]]></mp-video>`

Changing the videoid does not change the video, also calling the `_createVimeoPlayer()` or even the `ready()` function on the element with onChange observer on videoid also does not change anything (but does give a frogaaloops error)

**Comment by mpachnis** [comment]
Take a look on this example, is this what are you trying to do?
https://jsfiddle.net/mpachnis/ko1d9wy9/1/

**Comment by wouterz** [comment]
Sorry maybe I wassnt clear enough. More like this: 
https://jsfiddle.net/ko1d9wy9/4/

Change the video in the same player. The first video loads propperly, but doing the same thing with a new video-id, does not seem to change anything

**Comment by mpachnis** [comment]
The `createVimeoPlayer()` is to create the player, it builds the hole iframe element. So, every time you call it, it will create another (and anohter...) iframe element. So, you just need to get the current one and replace the videoId with a new one.

I update the example:
https://jsfiddle.net/mpachnis/ko1d9wy9/5/

**Comment by wouterz** [comment]
Thanks, that works perfectly!
